import React from 'react';
import { PageLayout } from '../components/PageLayout';
import { Card } from '../components/Card';
import { Button } from '../components/Button';
import { FileText, Download, Calendar, TrendingUp } from 'lucide-react';

const reportTypes = [
  { 
    id: 1, 
    title: 'Project Status Report', 
    description: 'Comprehensive overview of all active projects, their progress, and key metrics', 
    icon: <FileText className="w-6 h-6" />,
    frequency: 'Weekly'
  },
  { 
    id: 2, 
    title: 'Time Tracking Report', 
    description: 'Detailed breakdown of time logged by team members across projects and tasks', 
    icon: <Calendar className="w-6 h-6" />,
    frequency: 'Monthly'
  },
  { 
    id: 3, 
    title: 'Issue Analysis Report', 
    description: 'Analysis of issues by severity, status, and resolution time', 
    icon: <TrendingUp className="w-6 h-6" />,
    frequency: 'Bi-weekly'
  },
  { 
    id: 4, 
    title: 'Resource Utilization Report', 
    description: 'Team member allocation and workload distribution across projects', 
    icon: <FileText className="w-6 h-6" />,
    frequency: 'Monthly'
  },
  { 
    id: 5, 
    title: 'Budget Report', 
    description: 'Financial overview showing budget allocation, spending, and forecasts', 
    icon: <FileText className="w-6 h-6" />,
    frequency: 'Monthly'
  },
  { 
    id: 6, 
    title: 'Performance Report', 
    description: 'Team and individual performance metrics including velocity and completion rates', 
    icon: <TrendingUp className="w-6 h-6" />,
    frequency: 'Quarterly'
  },
];

export function Reports() {
  return (
    <PageLayout 
      title="Reports"
      actions={
        <Button>
          <Download className="w-4 h-4 mr-2" />
          Export All Reports
        </Button>
      }
    >
      <div className="space-y-6">
        <Card title="Quick Stats">
          <div className="grid grid-cols-4 gap-6">
            <div>
              <p className="text-[12px] text-[#6B7280] mb-1">Total Reports Generated</p>
              <p className="text-[24px] font-semibold text-[#1F2937]">142</p>
            </div>
            <div>
              <p className="text-[12px] text-[#6B7280] mb-1">Last Generated</p>
              <p className="text-[14px] font-medium text-[#1F2937]">2026-02-19 09:30</p>
            </div>
            <div>
              <p className="text-[12px] text-[#6B7280] mb-1">Scheduled Reports</p>
              <p className="text-[24px] font-semibold text-[#1F2937]">6</p>
            </div>
            <div>
              <p className="text-[12px] text-[#6B7280] mb-1">Custom Reports</p>
              <p className="text-[24px] font-semibold text-[#1F2937]">8</p>
            </div>
          </div>
        </Card>

        <div className="grid grid-cols-2 gap-6">
          {reportTypes.map((report) => (
            <Card key={report.id}>
              <div className="flex gap-4">
                <div className="w-12 h-12 bg-[#EFF6FF] rounded-[6px] flex items-center justify-center text-[#2563EB] flex-shrink-0">
                  {report.icon}
                </div>
                <div className="flex-1">
                  <h3 className="text-[16px] font-semibold text-[#1F2937] mb-1">{report.title}</h3>
                  <p className="text-[14px] text-[#6B7280] mb-3">{report.description}</p>
                  <div className="flex items-center justify-between">
                    <span className="text-[12px] text-[#6B7280]">
                      Frequency: <span className="font-medium text-[#1F2937]">{report.frequency}</span>
                    </span>
                    <div className="flex gap-2">
                      <Button size="sm" variant="outline">View</Button>
                      <Button size="sm">
                        <Download className="w-3 h-3 mr-1" />
                        Download
                      </Button>
                    </div>
                  </div>
                </div>
              </div>
            </Card>
          ))}
        </div>

        <Card title="Recent Report History">
          <div className="space-y-3">
            {[
              { name: 'Project Status Report', date: '2026-02-19 09:30', user: 'Sarah Johnson', type: 'PDF' },
              { name: 'Time Tracking Report', date: '2026-02-18 14:20', user: 'Michael Chen', type: 'Excel' },
              { name: 'Issue Analysis Report', date: '2026-02-17 11:15', user: 'Emily Rodriguez', type: 'PDF' },
              { name: 'Budget Report', date: '2026-02-16 10:00', user: 'David Park', type: 'Excel' },
            ].map((entry, index) => (
              <div key={index} className="flex items-center justify-between py-2 border-b border-[#E5E7EB] last:border-0">
                <div className="flex-1">
                  <p className="text-[14px] font-medium text-[#1F2937]">{entry.name}</p>
                  <p className="text-[12px] text-[#6B7280]">Generated by {entry.user} on {entry.date}</p>
                </div>
                <div className="flex items-center gap-3">
                  <span className="text-[12px] px-2 py-1 bg-[#F8FAFC] border border-[#E5E7EB] rounded-[6px]">{entry.type}</span>
                  <Button size="sm" variant="ghost">
                    <Download className="w-4 h-4" />
                  </Button>
                </div>
              </div>
            ))}
          </div>
        </Card>
      </div>
    </PageLayout>
  );
}
